
rules: 
  no-extra-semi: off
  eol-last": off

{
 "rules": {
    "quotes": ["error", "single", { "allowTemplateLiterals": true }]
 }
}

parserOptions:
  ecmaVersion: latest
  sourceType: 'module'

env:
  es2017: true
  browser: true

extends: 'htmlacademy/vanilla'
